### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by Jawnnypoo** [uber/AutoDispose#179]
Using `0.6.2`, ran into a new issue today:
```
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.uber.autodispose.LifecycleScopeProvider: can't find referenced class com.google.errorprone.annotations.DoNotMock
Warning: com.uber.autodispose.ScopeProvider: can't find referenced class com.google.errorprone.annotations.DoNotMock
Warning: there were 2 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details
```

Based on this [Stack Overflow post](https://stackoverflow.com/questions/45908252/dagger-android-support-proguard-rules) there probably just needs to be an additional rule in the proguard config that ships with the lifecycle artifact.
```
-dontwarn com.google.errorprone.annotations.**
```
I can make a PR, just wanted to discuss beforehand.

**Comment by hzsweers** [comment]
This is fixed in 0.6.1, which was just released!

**Comment by hzsweers** [comment]
Let me know if 0.6.1 solves this for you

**Comment by drakeet** [comment]
This problem still exists in v0.6.1. 
![image](https://user-images.githubusercontent.com/5214214/36638139-6386d70e-1a27-11e8-9571-3ceae67dd67b.png)

**Comment by hzsweers** [comment]
Consumer proguard rules are only included in the Android artifacts, they can't be bundled in jar-only artifacts. If you want to fix the proguard issue in your app and are only using the main autodispose artifact, you'll have to add the proguard rhles yourself.

**Comment by drakeet** [comment]
@hzsweers How about using aar and `consumerProguardFiles` for those Android library module?

**Comment by drakeet** [comment]
Sorry, I just noticed that consumerProguardFiles has been specified in these projects.
https://github.com/uber/AutoDispose/blob/master/android/autodispose-android/build.gradle#L29
But it is strange that they do not seem to take effect, I check what is the reason.

**Comment by hzsweers** [comment]
I'm going to close this out, feel free to ping if anyone still sees issues with android artifacts on 0.6.1+
